select FARMER.NAME,LAND.LAND_ID AS `LAND_ID`,CROP.CROP_NAME AS CROP_NAME FROM FARMER,LAND,CROP where FARMER.NAME=LAND.LAND_OWNER AND CROP.AADHAR_NUMBER=FARMER.AADHAR_NUMBER

select CROP.CROP_NAME,SEEDS.COMPANY AS SEEDS,FERTILISERS.COMPANY AS FERTILISERS,PESTICIDES.COMPANY AS PESTICIDES FROM CROP,SUM(SEEDS.PRICE,FERTILISERS.PRICE,PESTICIDES.PRICE),FERTILISERS,PESTICIDES,SEEDS WHERE CROP.CROP_ID=FERTILISERS.FERTILISER_ID AND CROP.CROP_ID=PESTICIDES.CROP_ID AND CROP.CROP_ID=SEEDS.CROP_ID 

SELECT 
    CROP.CROP_NAME,
    SEEDS.COMPANY AS SEEDS,
    FERTILISERS.COMPANY AS FERTILISERS,
    PESTICIDES.COMPANY AS PESTICIDES,
    (SEEDS.PRICE + FERTILISERS.PRICE + PESTICIDES.PRICE) AS TOTAL_PRICE
FROM 
    CROP
    INNER JOIN SEEDS ON CROP.CROP_ID = SEEDS.CROP_ID
    INNER JOIN FERTILISERS ON CROP.CROP_ID = FERTILISERS.CROP_ID
    INNER JOIN PESTICIDES ON CROP.CROP_ID = PESTICIDES.CROP_ID;

SELECT farmer.NAME,agrostore.STORE_NAME,agrostore.LOCATION FROM farmer INNER JOIN agrostore ON  farmer.PINCODE=agrostore.PINCODE

SELECT 
    farmer.name,
    queryh.content,
    answer.ANSWER_CONTENT,
    expert.NAME
FROM 
    farmer 
    INNER JOIN queryh ON queryh.`AADHAR_NUMBER` = farmer.`AADHAR_NUMBER`
    INNER JOIN answer ON queryh.QUERY_ID = answer.QUERY_ID
    INNER JOIN expert ON answer.`EXPERT_AADHAR` = expert.`AADHAR_NUMBER`;

